version: '2'
services:
  web:
    image: moodle-udc-levin:latest
    ports:
      - 7580:80
    volumes:
      - moodledata:/moodledata
      # do not uncomment this when starting a new instance from scratch as
      # init script won't be able to move this file
      #- ./LocalSettings.php:/var/www/html/LocalSettings.php
    environment:
      - MOODLE_DB_TYPE=mysql
      - MOODLE_DB_HOST=rc1b-71oajha2w0jm5ap2.mdb.yandexcloud.net
      - MOODLE_DB_PORT=3306
      - MOODLE_DB_NAME=moodle-one
      - MOODLE_DB_USER=moodle-one
      - MOODLE_DB_PASSWORD=098fh93jfk
      - MOODLE_DB_PREFIX=
      - MOODLE_URL=http://localhost:7580
      #- MOODLE_SITE_FULLNAME=
      #- MOODLE_SITE_SHORTNAME=
      #- MOODLE_SITE_LANG=
      #- MOODLE_ADMIN_USER=
      #- MOODLE_ADMIN_PASS=
      #- MOODLE_ADMIN_EMAIL=
      #- MOODLE_UPDATE=
      #- MOODLE_REVERSE_PROXY=false
      #- MOODLE_SSL_PROXY=false
      - MOODLE_REDIS_HOST=redis
      - MOODLE_REDIS_PORT=6379
      - MOODLE_REDIS_DB=0
      #- MOODLE_REDIS_PREFIX=''
      - MOODLE_DISABLE_UPDATE_AUTODEPLOY=true
      #- MOODLE_DEBUG=true
      #- SMTP_HOST=example.com:465
      #- SMTP_USER=test
      #- SMTP_PASS=testpass
      #- SMTP_SECURITY=ssl
      #- SMTP_AUTH_TYPE=PLAIN
      #- MOODLE_NOREPLY_ADDRESS=test@example.com
  redis:
    image: redis:5.0-alpine
    volumes:
      - ./.data/redis:/data
    ports:
      - 6379:6379
      
volumes:
  moodledata:
