version: '2'
services:
  moodle:
    image: docker.io/bitnami/moodle:3
    ports:
      - '80:8080'
      - '443:8443'
    environment:

      - MOODLE_DATABASE_TYPE=mysqli
      - MOODLE_DATABASE_HOST=rc1b-71oajha2w0jm5ap2.mdb.yandexcloud.net
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=moodle-one
      - MOODLE_DATABASE_NAME=moodle-one
      - MOODLE_DATABASE_PASSWORD=098fh93jfk
      - MOODLE_SKIP_BOOTSTRAP=yes

    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
volumes:
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
