version: '3.8'

services:
  ubuntu:
    stdin_open: true
    tty: true
    restart: unless-stopped
    image: ubuntu
    command:
      - /bin/sh 
      - -c 
      - |
        date &&
        ls -lh &&
        apt update &&
        apt install -y git &&
        /bin/sh
