version: '3.8'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2022-03-26T06-49-28Z
  command: server --console-address ":9001" http://minio{1...6}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: adminnn
    MINIO_ROOT_PASSWORD: zxcDFrt56
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3
  
  
# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    ports:
      - "9010:9000"
      - "9011:9001"
    deploy:
      placement:
        max_replicas_per_node: 1
        constraints: [node.hostname == srv35-privatecloud-internat-msu-ru]
    

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2
    ports:
      - "9020:9000"
      - "9021:9001"
    deploy:
      placement:
        max_replicas_per_node: 1
        constraints: [node.hostname == srv36-privatecloud-internat-msu-ru]
  
  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - data3-1:/data1
      - data3-2:/data2
    ports:
      - "9030:9000"
      - "9031:9001"
    deploy:
      placement:
        max_replicas_per_node: 1
        constraints: [node.hostname == srv37-privatecloud-internat-msu-ru]
  
  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - data4-1:/data1
      - data4-2:/data2
    ports:
      - "9040:9000"
      - "9041:9001"
    deploy:
      placement:
        max_replicas_per_node: 1
        constraints: [node.hostname == srv38-privatecloud-internat-msu-ru]
        
  minio5:
    <<: *minio-common
    hostname: minio5
    volumes:
      - data5-1:/data1
      - data5-2:/data2
    ports:
      - "9050:9000"
      - "9051:9001"
    deploy:
      placement:
        max_replicas_per_node: 1
        constraints: [node.hostname == srv39-privatecloud-internat-msu-ru]
        
  minio6:
    <<: *minio-common
    hostname: minio6
    volumes:
      - data6-1:/data1
      - data6-2:/data2
    ports:
      - "9060:9000"
      - "9061:9001"
    deploy:
      placement:
        max_replicas_per_node: 1
        constraints: [node.hostname == srv21-privatecloud-internat-msu-ru]
        
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    #volumes:
    #  - etc-nginx:/etc/nginx/nginx.conf
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
      - minio5
      - minio6
    configs:
      - source: nginx-minio
        target: /etc/nginx/nginx.conf
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        #constraints: [node.role == manager]
     

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:
  data5-1:
  data5-2:
  data6-1:
  data6-2:
  
configs:
  nginx-minio:
    external:
      name: nginx-minio
