version: '2'
services:
  postgresql:
    stdin_open: true
    tty: true
    
    image: docker.io/bitnami/postgresql:13
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      
      - POSTGRESQL_CLIENT_DATABASE_HOST=rc1b-2xw3ho4xlcer3p7t.mdb.yandexcloud.net
      - POSTGRESQL_CLIENT_DATABASE_PORT_NUMBER=6432
      - POSTGRESQL_CLIENT_POSTGRES_USER=odoo
      - POSTGRESQL_CLIENT_POSTGRES_PASSWORD=hg983tfg80943fg893
      
      - POSTGRESQL_HOST=rc1b-2xw3ho4xlcer3p7t.mdb.yandexcloud.net
      - POSTGRESQL_PORT_NUMBER=6432
      - POSTGRESQL_CLIENT_ROOT_USER
      - POSTGRESQL_POSTGRES_USER=odoo
      - POSTGRESQL_ROOT_USER=odoo
      - POSTGRESQL_CLIENT_ROOT_PASSWORD=hg983tfg80943fg893
      - POSTGRESQL_POSTGRES_PASSWORD=hg983tfg80943fg893
      - POSTGRESQL_ROOT_PASSWORD=hg983tfg80943fg893
      
      
      - BITNAMI_DEBUG=true
      
  odoo:
    stdin_open: true
    tty: true
    
    #restart: unless-stopped
    image: docker.io/bitnami/odoo:14
    ports:
      - '8079:8069'
    volumes:
      - 'odoo_data:/bitnami/odoo'
      
    depends_on:
      - postgresql
    environment:
      #- ALLOW_EMPTY_PASSWORD=yes
      - ALLOW_MASTER_PASSWORD=yes
      
      #- ODOO_DATABASE_HOST=rc1b-2xw3ho4xlcer3p7t.mdb.yandexcloud.net
      #- ODOO_DATABASE_PORT_NUMBER=6432
      #- ODOO_DATABASE_NAME=odoo
      #- ODOO_DATABASE_USER=odoo
      #- ODOO_DATABASE_PASSWORD=hg983tfg80943fg893
       
      #- POSTGRESQL_HOST=rc1b-2xw3ho4xlcer3p7t.mdb.yandexcloud.net
      #- POSTGRESQL_PORT_NUMBER=6432
      #- POSTGRESQL_DATABASE_NAME=odoo
      #- POSTGRESQL_DATABASE_USER=odoo
      #- POSTGRESQL_DATABASE_USERNAME=odoo
      #- POSTGRESQL_DATABASE_PASSWORD=hg983tfg80943fg893
      
      #- ODOO_DATABASE_ADMIN_PASSWORD=hg983tfg80943fg893
      - ODOO_DATABASE_HOST=rc1b-2xw3ho4xlcer3p7t.mdb.yandexcloud.net
      - ODOO_DATABASE_PORT_NUMBER=6432
      - ODOO_DATABASE_USER=odoo
      #- ODOO_DATABASE_NAME=odoo
      - ODOO_DATABASE_PASSWORD=hg983tfg80943fg893

      #- ODOO_SKIP_BOOTSTRAP=yes
      #- ODOO_SKIP_MODULES_UPDATE=yes
      - BITNAMI_DEBUG=true

volumes:
  postgresql_data:
    driver: local
  odoo_data:
    driver: local
    
    
    
    
    
