version: '3.1'
services:
  setup-certificate-psql:
    container_name: setup-certificate-psql-container
    image: ubuntu
    restart: unless-stopped
    stdin_open: true
    tty: true
    command:
      - /bin/sh
      - -c 
      - |
        apt update &&
        apt install -y wget &&
        wget https://storage.yandexcloud.net/cloud-certs/CA.pem --output-document=/root/.postgresql/root.crt && 
        chmod 0666 /root/.postgresql/root.crt &&
        apt install -y python3 &&
        (python3 -m http.server --cgi 3000 &> /dev/null 2>&1 & ) &&
        /bin/sh  
    volumes:
      - certificate-psql:/root/.postgresql
    networks:
      - wait-for-it-net
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  web:
    stdin_open: true
    tty: true
    depends_on:
      - setup-certificate-psql
    image: odoo:14.0
    ports:
      - "8094:8069"
    environment:
      - HOST=rc1b-2xw3ho4xlcer3p7t.mdb.yandexcloud.net
      - USER=odoo
      - PASSWORD=hg983tfg80943fg893
      - PORT=6432
    volumes:
      - odoo-web-data:/var/lib/odoo
      - odoo-config:/etc/odoo
      - odoo-addons:/mnt/extra-addons
      - odoo-local-bin:/usr/local/bin
      - certificate-psql:/root/.postgresql
    networks:
      - wait-for-it-net
      
volumes:
  odoo-web-data:
  odoo-config:
  odoo-addons:
  odoo-local-bin:
  certificate-psql:
networks:
  wait-for-it-net:
